name: ci-client

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'src/client/**'
      - '!src/client/.devcontainer/**'
      - '!src/client/.vscode/**'
      - '!src/client/.gitignore'
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'src/client/**'
      - '!src/client/.devcontainer/**'
      - '!src/client/.vscode/**'
      - '!src/client/.gitignore'
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install python dependencies
        working-directory: src/client
        run: |
          python -m pip install --upgrade pip
          pip install pylint pyinstaller
          pip install -r requirements.txt
      - name: Lint with pylint
        working-directory: src/client
        run: pylint app --rcfile=.pylintrc --exit-zero
      - name: Create executables
        working-directory: src/client
        run: pyinstaller app/__main__.py --onefile -n client
      - name: Run executable with --version command
        working-directory: src/client/dist
        run: ./client --version 
      - name: Run executable with --help command
        working-directory: src/client/dist
        run: ./client --help 
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: client-${{ matrix.os }}
          path: src/client/dist/*
