name: ci-server

on:
  push:
    paths:
      - '.github/workflows/**'
      - 'src/server/**'
      - '!src/app/.devcontainer/**'
      - '!src/app/.vscode/**'
      - '!src/app/.gitignore'
    branches:
      - master
  pull_request:
    paths:
      - '.github/workflows/**'
      - 'src/server/**'
      - '!src/app/.devcontainer/**'
      - '!src/app/.vscode/**'
      - '!src/app/.gitignore'
  workflow_dispatch:

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: src/server
        run: |
          python3 --version
          python3 -m pip install --upgrade pip
          pip3 install pylint pyinstaller
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
      - name: Lint with pylint
        working-directory: src/server
        run: pylint app
      - name: Create executables
        working-directory: src/server
        run: pyinstaller app/__main__.py --onefile -n server --hidden-import thespian.system.multiprocTCPBase 
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: server-${{ matrix.os }}
          path: src/server/dist/*
