name: release

on:
  push:
    branches:
      - master
    tags:
      - '*'
  workflow_dispatch:

jobs:
  build-documentation:
    name: Build documentation pdf file
    runs-on: ubuntu-18.04
    container:
      image: skyfrk/udhbwvst:5.3.4
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Display versions of build tools
        run: |
          latexmk -v
          lualatex --version
          java -jar $PLANTUML_JAR -version
      - name: Build
        run: |
          latexmk \
          -pdf \
          -file-line-error \
          -interaction=nonstopmode \
          -cd \
          -pdflatex=lualatex \
          -synctex=1 \
          -shell-escape \
          src/documentation/root.tex
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: documentation
          path: src/documentation/root.pdf

  build-server:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, windows-2019, macos-10.15]
    container:
      image: mcr.microsoft.com/vscode/devcontainers/python:0-3
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        working-directory: src/server
        run: |
          python3 -m pip install --upgrade pip
          pip3 install pylint pyinstaller
          if [ -f requirements.txt ]; then pip3 install -r requirements.txt; fi
      - name: Lint with pylint
        working-directory: src/server
        run: pylint app
      - name: Create executables
        working-directory: src/server
        run: pyinstaller app/__main__.py --onefile -n server --hidden-import thespian.system.multiprocTCPBase 
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: server-${{ matrix.os }}
          path: src/server/dist/*

  deploy:
    if: startsWith(github.ref, 'refs/tags/')
    name: Deploy to GitHub Releases
    needs: [ build-documentation, build-server ]
    runs-on: ubuntu-18.04
    steps:
      - name: Download
        uses: actions/download-artifact@v2
        with:
          path: artifacts
      - name: Prepare
        run: |
          mkdir staging
          mv artifacts/documentation/root.pdf "staging/WWI17B_Seminararbeit_ABE1_Gruppe_B1-${GITHUB_REF##*/}.pdf"
          mv artifacts/server** staging
      - name: Deploy
        uses: softprops/action-gh-release@v1
        with:
          files: staging/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
